package app.chatwave.me.UtilityPackage;

public class SoundList {

    public static String[][] mSoundList = {
            {"Absolutely not", "Absolutely_not.mp3"},
        {"Alright thats enough", "Alright_thats_enough.mp3"},
        {"And we push it", "And_we_push_it.mp3"},
        {"Oh my damn", "Oh_my_damn.mp3"},
        {"Better closer warmer", "Better_closer_warmer.mp3"},
        {"Check it out", "Check_it_out.mp3"},
        {"Dont worry about it", "Dont_you_worry_about_it.mp3"},
        {"Go", "Go.mp3"},
        {"Hey", "Hey.mp3"},
        {"Hey how ya doin", "Hey_how_ya_doin.mp3"},
        {"Hold on a second", "Hold_on_a_second.mp3"},
        {"Im in charge", "I_am_the_one_whos_in_charge.mp3"},
        {"I dont care", "I_dont_care.mp3"},
        {"I dont know", "I_dont_know.mp3"},
        {"I dont think so", "I_dont_think_so.mp3"},
        {"I love you", "I_love_you.mp3"},
        {"I remember that", "I_remember_that.mp3"},
        {"I was improvising", "I_was_improvising.mp3"},
        {"I was neglected", "I_was_neglected.mp3"},
        {"Im not wit dat", "Im_not_wit_dat.mp3"},
        {"Sorry I made a mistake", "Im_sorry_I_apologize_I_made_a_mistake.mp3"},
        {"No idea what Im talking about", "Im_sure_you_have_no_idea_what_Im_talking_about.mp3"},
        {"Im warning ya", "Im_warning_ya.mp3"},
        {"It was a nightmare", "It_was_a_nightmare.mp3"},
        {"Its a smash hit", "Its_a_smash_hit.mp3"},
        {"Its like that seriously", "Its_like_that_seriously.mp3"},
        {"Jack it up", "Jack_it_up.mp3"},
        {"Me baby me", "Me_baby_me.mp3"},
        {"Mhmm", "Mhmm.mp3"},
        {"Dont be a jerk", "My_friend_dont_be_a_jerk.mp3"},
        {"Oh shut up", "Oh_shut_up.mp3"},
        {"Ok lets go", "Ok_lets_go.mp3"},
        {"Please", "Please.mp3"},
        {"Really", "Really.mp3"},
        {"Respect", "Respect.mp3"},
        {"See ya later", "See_ya_later.mp3"},
        {"So easy", "So_easy.mp3"},
        {"So whatcha sayin", "So_whatcha_sayin.mp3"},
        {"Sometimes", "Sometimes.mp3"},
        {"Stop", "Stop.mp3"},
        {"Thats disgusting", "Thats_disgusting.mp3"},
        {"Thats it", "Thats_it.mp3"},
        {"Thats right", "Thats_right.mp3"},
        {"Silly and ridiculous", "Thats_silly_thats_ridiculous.mp3"},
        {"Think about it man", "Think_about_it_man.mp3"},
        {"Your spare time", "This_is_what_you_do_with_your_spare_time.mp3"},
        {"Tough guy", "Tough_guy.mp3"},
        {"Well hurry up", "Well_hurry_up.mp3"},
        {"What", "What.mp3"},
        {"What are you doing", "What_are_you_doing.mp3"},
        {"WTF", "What_the_fuck.mp3"},
        {"Whateva man", "Whateva_man.mp3"},
        {"Yeah", "Yeah.mp3"},
        {"Strange thing", "Yeah_thats_a_strange_thing_to_do.mp3"},
        {"Yeah you could say that", "Yeah_you_could_say_that.mp3"},
        {"You and me", "You_and_me.mp3"},
        {"You're good looking", "You_are_good_looking_you_are_handsome.mp3"},
        {"You dont understand", "You_dont_understand.mp3"},
        {"You prick", "You_prick.mp3"},
        {"Think that was cool", "You_think_that_was_cool.mp3"},
        {"Yup", "Yup.mp3"}
    };
}